### ISSUE TITLE
This content failed to load.

### ISSUE THREAD

**Issue by denda888** [scriptua/magento2-quickview#1]
![screenshot from 2017-12-29 15-57-57](https://user-images.githubusercontent.com/30828860/34433322-153feff2-ecb1-11e7-9657-83aca95523df.png)

I'm using this module with magento 2.1.9 but it fails like this, I have followed the upgrade / compile / static-content steps.
hope the helping. thank you

**Comment by scriptua** [comment]
Everything should work.
You have installed scriptua/magento2-base ?

**Comment by denda888** [comment]
oh thanks, i installed scriptua / magento2-base and everything worked fine. Thanks very much
