### ISSUE TITLE
There is one error in this

### ISSUE THREAD

**Issue by sassassassas** [scriptua/magento2-quickview#2]
Exception #0 (ReflectionException): Class Magento\Framework\View\Design\Theme\ThemeList does not exist

**Comment by scriptua** [comment]
This is a versioning-dependency error. It has already been fixed, first remove the module:
````
composer remove scriptua/magento2-base
bin/magento setup:upgrade
````
and then reinstall it:
````
composer require scriptua/magento2-quickview
bin/magento module:enable Script_Base
bin/magento module:enable Script_QuickView
bin/magento setup:upgrade
````

If there is an error on the site, change the location of the Script_Base (schema_version, data_version) from 1.0.3 to 1.0.2 in your database in the setup_module table.

**Comment by sassassassas** [comment]
I changed Script_Base (schema_version, data_version) from 1.0.3 to 1.0.2 and now its showing this error

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Script_Base schema: current version - 1.0.2, required version - 1.0.3
Script_Base data: current version - 1.0.2, required version - 1.0.3

**Comment by scriptua** [comment]
Above, I wrote that I would need to update the database

> If there is an error on the site, change the location of the Script_Base (schema_version, data_version) from 1.0.3 to 1.0.2 in your database in the setup_module table.

**Comment by sassassassas** [comment]
I get to know that when i am using my custom theme its not working at  frontend but when i am using Magento/blank or Magento/luma its working fine.

**Comment by sassassassas** [comment]
![frontend](https://user-images.githubusercontent.com/34996615/34467118-3ab1ea6a-ef0e-11e7-9397-9dc2672815f0.png)
I am getting this error

**Comment by scriptua** [comment]
Try it now
````
bin/magento setup:static-content:deploy
````

**Comment by sassassassas** [comment]
Still the same issue

**Comment by scriptua** [comment]
This may be theme issue. You need to look more closely. If possible, can I look at this error.

**Comment by sassassassas** [comment]
This issue is resolved i was uploading wrong css file in my custom theme .Thanks for your help.Nice work
