### ISSUE TITLE
Configurable Product Switch to Price issue

### ISSUE THREAD

**Issue by ChandrakantDevani** [scriptua/magento2-quickview#23]
Magento Version 2.2.4

First I open to complete Price get and after i switch product size to price get in minus.

This issue is only in quick view popup and also bundle product option not show in popup.

I attached some screenshot:

First time load product
http://prntscr.com/np7jab

After Product Size switch
http://prntscr.com/np7jjs
http://prntscr.com/np7k0c

Bundle Product Quick view Popup
http://prntscr.com/np7l35

Thanks,
Chandrakant

**Comment by hryvinskyi** [comment]
@ChandrakantDevani I can't reproduce this issue
