### ISSUE TITLE
Cant find the Script_Base Module.

### ISSUE THREAD

**Issue by monikav-dckap** [scriptua/magento2-quickview#24]
Hi, Where can I download the Script_Base module? While downloading I got only Script_QuickView Module.

**Comment by hryvinskyi** [comment]
Hi, You can download Script_Base in this repository: https://github.com/hryvinskyi/magento2-base/tree/v1.1.2 or https://github.com/hryvinskyi/magento2-base/archive/v1.1.2.zip
