### ISSUE TITLE
Product image bug

### ISSUE THREAD

**Issue by deadlyw1re** [scriptua/magento2-quickview#7]
When you open the pop-up and click on the product image the image will get loaded in another popup behind the product popup.

![peek 2018-06-13 10-30](https://user-images.githubusercontent.com/23723417/41339320-ceaec8c6-6ef4-11e8-89af-c7a6044c2142.gif)

**Comment by scriptua** [comment]
fixed: https://github.com/scriptua/magento2-quickview/commit/675daa46628b54695c4b3e60e0cbd35a7d4841a2
