### ISSUE TITLE
Configurable Product Image issue 

### ISSUE THREAD

**Issue by ChandrakantDevani** [scriptua/magento2-quickview#8]
I have click product option to image does't change.

show error in console

![capture](https://user-images.githubusercontent.com/28138615/41533888-03e5d1aa-731a-11e8-9838-5eaa74831417.PNG)

**Comment by scriptua** [comment]
@ChandrakantDevani Fixed https://github.com/scriptua/magento2-quickview/commit/e766e118a676b005227db97e3e9131d626c4ed0a
